package cn.lynu.lyq.signin.model;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Assignment generated by MyEclipse Persistence Tools
 */
@Entity
public class Assignment implements java.io.Serializable {
	private static final long serialVersionUID = -8128536809297019985L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	
	@ManyToOne(cascade=CascadeType.MERGE)
	@JoinColumn(name="stu_id")
	private Student student;

	private Date submitdate;

	private String filepath;

	private String comments;

	// Constructors

	/** default constructor */
	public Assignment() {}

	/** minimal constructor */
	public Assignment(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Assignment(Integer id, Student student, Date submitdate,
			String filepath, String comments) {
		this.id = id;
		this.student = student;
		this.submitdate = submitdate;
		this.filepath = filepath;
		this.comments = comments;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Date getSubmitdate() {
		return this.submitdate;
	}

	public void setSubmitdate(Date submitdate) {
		this.submitdate = submitdate;
	}

	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}